### ISSUE TITLE
Cannot make StickyHeaders work in containerized adminer

### ISSUE THREAD

**Issue by Thomas-Ganter** [derStephan/AdminerPlugins#1]
I am probably too stupid to do this, getting it to work with [the official image](https://hub.docker.com/_/adminer).

I have created a file in the ```plugins-enabled``` folder like this: 
```php
<?php

   require_once('plugins-enabled/.included/stickyColumns.php');
   return new stickyColumns("_rowid","", true); 
?>
```
This is even loaded (I have checked) but takes no effect.

**Comment by derStephan** [comment]
Hi Thomas,

thank you for trying stickyColumns. Do other plugins work for you? 

Did you follow the steps given here: 
https://www.adminer.org/en/plugins/#use

If you follow that word by word, then you should have an array named `$plugins`. 

```
$plugins = array(
	new stickyColumns("_rowid","",true)
);
```

Best regards
Stephan

**Comment by derStephan** [comment]
Wait, I just understood that you are running a docker image. I would like to point out that this is a user contributed image and no official one. 

I wonder why anyone would use a docker image for something that is meant to be a single-file application. This seems like the exact opposite of what adminer is supposed to be. 

Anyway, after scanning the short introduction of that image it seems that plugin handling within that image is somewhat different than it is with the official single php-file. I am afraid I can not help you with that because I do not have any experience with it. Maybe you should ask the maintainer of the docker image how to add custom plugins.

**Comment by derStephan** [comment]
Yet another question. 

Is there a column `_rowid` that should stick to the left? If not, it will just do nothing.

**Comment by derStephan** [comment]
@Thomas-Ganter any news on this issue? Otherwise I would like to close it.

**Comment by Thomas-Ganter** [comment]
I am still experimenting. You can close the Issue and I could post an update here if I make it happen.

**Comment by Thomas-Ganter** [comment]
Finally — I could make it work. 
The culprit was another Plugin that returned `true` from the `head()` function. 

Sorry to have suspected your plugin.

**Comment by derStephan** [comment]
ah, perfect. Does it work as expected?

**Comment by Thomas-Ganter** [comment]
Yep.  
Thanks.  
And Sorry for the confusion.  

(I may need to explicitly set white backgrounds on the sticky cells, but again this might be a conflict so I will first look into it and then post a complaint.)
